"""Ajout du champ age dans User

Revision ID: 3c8b2d03b1a7
Revises: 
Create Date: 2025-08-08 16:46:14.442307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c8b2d03b1a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_table')
    op.drop_table('logs')
    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etat_categorie', sa.String(length=100), nullable=False))

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('nom',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('prenom',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['nom'])
        batch_op.drop_column('mdp')
        batch_op.drop_column('id_profil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_profil', mysql.MEDIUMINT(display_width=9), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mdp', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('prenom',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('nom',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.drop_column('etat_categorie')

    op.create_table('logs',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('logs', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('date_time', mysql.DATETIME(), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip_adresse', mysql.VARCHAR(length=50), nullable=False, comment='adresse ip'),
    sa.Column('operating_system', mysql.VARCHAR(length=100), nullable=False, comment='se'),
    sa.Column('browser_used', mysql.VARCHAR(length=100), nullable=False, comment='navigateur'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('session_table',
    sa.Column('id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
