"""ajouter une table materiel

Revision ID: c5a849bd6abe
Revises: 3c8b2d03b1a7
Create Date: 2025-08-08 17:13:16.559486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a849bd6abe'
down_revision = '3c8b2d03b1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_mat', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiel', schema=None) as batch_op:
        batch_op.drop_column('nom_mat')

    # ### end Alembic commands ###
